import React from "react"
import { useLocation } from "react-router-dom"
import "./styles/main.css"

export default function PitchDetails() {
  const location = useLocation();
  const isEnglish = location.pathname.includes('/pitch-details-en');

  if (isEnglish) {
    return (
      <div className="pitch-details">
        <div className="container">
          <header className="pitch-header">
            <h1>nicetone.ai Business Proposal</h1>
            <p className="pitch-tagline">AI English Training Platform Monetizing Voice Data</p>
          </header>

          <section className="pitch-section">
            <h2>Executive Summary</h2>
            <p>
              nicetone.ai is an AI English training platform that monetizes voice data, offering near-free services with flywheel effects. 
              We focus on English pronunciation learning, combining Microsoft Azure speech technology with proprietary AI analysis to provide 
              professional-grade assessment, personalized recommendations, and cross-device learning experiences for global language learners. 
              Our core mission is to solve traditional English learning pain points: lack of real-time feedback, scarce professional resources, 
              and high costs. This model monetizes high-quality voice data generated by users, creating a flywheel effect: 
              More Users → More Data → Higher Revenue → Lower Costs → Attract More Users, expected to create sustainable growth and attract investors.
            </p>
            
            <div className="key-points">
              <h3>Key Highlights:</h3>
              <ul>
                <li><strong>Market Opportunity:</strong> $60 billion global language learning market, targeting 50 million users</li>
                <li><strong>Target:</strong> 20% market share, expanding to 34 languages in 10 years, reaching 10 million active users</li>
                <li><strong>Revolutionary Data Monetization:</strong> Voice data sales generate 100x higher profit margin than traditional speech recognition services. While processing costs $0.01 per minute, selling the same data generates $1+ per minute to AI companies, creating unprecedented profit margins</li>
                <li><strong>Integrated Business Model:</strong> Data-first revenue strategy combining voice data sales (primary), B2C subscriptions ($10 USD/month with data-for-free exchange), B2B solutions, API integration, white-label licensing, and strategic partnerships</li>
                <li><strong>Competitive Advantage:</strong> Top-tier technology integration (Azure deep cooperation), personalized user experience, and data-driven ecosystem</li>
                <li><strong>Financial Projection:</strong> $125 million annual revenue within 3 years, 25% net profit margin, expected ROI up to 300%</li>
                <li><strong>Funding Need:</strong> Seeking $5 million seed round for product optimization, market expansion, and data infrastructure</li>
              </ul>
            </div>
          </section>

          <section className="pitch-section">
            <h2>Market Pain Points</h2>
            <p>The current English pronunciation learning market faces core challenges:</p>
            
            <div className="pain-point">
              <h3>1. Low Traditional Learning Efficiency</h3>
              <p>Lack of personalized feedback and scientific assessment, learners struggle with phoneme error self-diagnosis.</p>
              <ul>
                <li>Unable to provide precise real-time pronunciation assessment</li>
                <li>Lack of phoneme-level error analysis</li>
                <li>Learners struggle with pronunciation problem self-diagnosis</li>
                <li>Traditional teaching cannot cater to individual needs</li>
              </ul>
            </div>

            <div className="pain-point">
              <h3>2. Scarce and Expensive Professional Resources</h3>
              <p>Quality pronunciation teaching resources are difficult to obtain, professional guidance is costly.</p>
              <ul>
                <li>Shortage of professional pronunciation teachers</li>
                <li>Expensive one-on-one guidance</li>
                <li>Geographic limitations restrict learning opportunities</li>
                <li>Lack of standardized assessment tools</li>
              </ul>
            </div>

            <div className="pain-point">
              <h3>3. High Global Language Learner Dropout Rate</h3>
              <p>These pain points lead to a global language learner dropout rate as high as 50%, with unmet market demand. Compared to engsight-lab.com (focusing on globalized language learning), we focus more on AI-driven real-time assessment and data monetization.</p>
            </div>
          </section>

          <section className="pitch-section">
            <h2>Solution</h2>
            <p>nicetone.ai provides a comprehensive AI pronunciation learning platform based on Microsoft Azure speech services and proprietary AI algorithms:</p>

            <div className="solution-feature">
              <h3>1. Smart Pronunciation Assessment Engine</h3>
              <p>Four-dimensional scoring (accuracy, fluency, completeness, prosody), phoneme-level analysis, real-time feedback.</p>
            </div>

            <div className="solution-feature">
              <h3>2. AI Personalized Learning Assistant</h3>
              <p>Analyzes learning progress, provides dynamic content recommendations, error pattern recognition, and progress tracking.</p>
            </div>

            <div className="solution-feature">
              <h3>3. Cloud Collaborative Ecosystem</h3>
              <p>Cross-device synchronization, community sharing, and enterprise management tools.</p>
            </div>

            <div className="solution-feature">
              <h3>4. Innovative Educational Model</h3>
              <p>Replace single exams with learning progress, support API integration into LMS systems (such as teachify.tw online course platform, seamlessly embedding our API).</p>
            </div>

            <div className="solution-feature">
              <h3>5. Core Functions</h3>
              <p>Real-time recording assessment, multi-modal input (text, voice, images), speech synthesis, favorites system, and AI assistant.</p>
            </div>

            <p>Platform designed modularly, ensuring scalability and flexibility for future expansion.</p>
          </section>

          <section className="pitch-section">
            <h2>Current Product Progress</h2>
            <p>Product development is almost complete, except for multi-language support, learning progress tracking, Widget and API integration that are not yet finished. Most functions are ready, including core pronunciation assessment engine, AI learning assistant, cloud sync, and user interface, ready to enter market testing and optimization phase.</p>
          </section>

          <section className="pitch-section">
            <h2>Market Opportunity</h2>
            <ul>
              <li><strong>Global Market:</strong> $60 billion scale, targeting 50 million users, 30,000 enterprise clients, 20% market share</li>
              <li><strong>Global Expansion:</strong> Support 34 languages, target 10 million active users, $1.5 billion annual revenue, 10-year deployment</li>
              <li><strong>Digital Learning Trends:</strong> 30% growth post-COVID and AI education demand (expected market of $600 billion) provide enormous opportunities. Drawing from ycombinator.com (Mathos AI math learning tool emphasizing personalized education), we focus on adaptive learning in the speech field.</li>
            </ul>
          </section>

          <section className="pitch-section">
            <h2>Business Model</h2>
            <p>Our revolutionary business model prioritizes voice data monetization with 100x profit margins over traditional speech processing. While Azure speech recognition costs $0.01 per minute, we can sell the same anonymized error data for $1+ per minute to AI companies, creating unprecedented profitability. This data-first strategy enables us to offer near-free services while building sustainable revenue streams across B2C, B2B, and B2B2C segments.</p>

            <div className="business-model">
              <h3>1. Voice Data Sales (Voice Data Monetization)</h3>
              <p><strong>Revolutionary Economics:</strong> 100x profit margin advantage - Azure processing costs $0.60/hour while data sales generate $60-300/hour for the same audio content.</p>
              <p><strong>Premium Data Value:</strong> Error pronunciation segments are worth $100-500 per hour to AI companies training speech recognition models, as incorrect pronunciation data is extremely rare and valuable.</p>
              <p><strong>Massive Profit Potential:</strong> Expected monthly 100 hours of premium data sales generating $10,000-30,000 USD with operational costs under $300, creating 97%+ gross margins.</p>
              <p><strong>Flywheel Effect:</strong> Free users generate valuable data → High-margin sales revenue → Subsidize free services → Attract more users → Exponential data value growth.</p>
            </div>

            <div className="business-model">
              <h3>2. B2C Subscription Service</h3>
              <p><strong>Basic Pricing:</strong> $10 USD/month (unlimited assessments, AI assistant, cloud sync)</p>
              <p><strong>High-Usage Free Clause:</strong> If users use more than 5 hours per month (e.g., total practice recording time), they can use that month for free. However, the Terms of Service clearly state: user voice data will be anonymized to assist in creating speech recognition engines (e.g., training AI models), and must meet high-quality conditions (average 80+ score sentences, only occasional incorrect pronunciation words). This encourages high engagement, generates more niche data (error pronunciation segments), and complies with privacy regulations (such as GDPR).</p>
              <p><strong>Expected Effect:</strong> Attract price-sensitive users, increase conversion rate by 20%; expected data consent rate of 30%, generating hundreds of hours of sellable linguistic data monthly.</p>
            </div>

            <div className="business-model">
              <h3>3. B2B Enterprise Solutions</h3>
              <p><strong>Pricing:</strong> From $3,000 USD/year (customized features, management dashboard, reports)</p>
              <p><strong>Refund Condition:</strong> Full refund if 1000 hours of analyzable content is reached (condition: average 80+ score sentences, only occasional incorrect pronunciation words). This encourages enterprises to generate high-quality data for our data sales channel.</p>
              <p><strong>Target:</strong> Corporate employee training and educational institutions.</p>
            </div>

            <div className="business-model">
              <h3>4. Teaching API Integration Service</h3>
              <p><strong>Pricing:</strong> $6 USD/month/student (API calls, grade analysis, support)</p>
              <p><strong>Refund Condition:</strong> 100% refund if 5 hours of analyzable content is reached (condition: average 80+ score sentences, only occasional incorrect pronunciation words). This part is paid by student parents, but teachers can receive rebates (points in mall for products like educational tools or course resources).</p>
              <p><strong>Function:</strong> Seamlessly embed into LMS systems (such as teachify.tw integration compatibility).</p>
              <p><strong>Expected Effect:</strong> Teacher incentive mechanisms increase adoption rate by 20%, while generating more high-quality data.</p>
            </div>

            <div className="business-model">
              <h3>5. White Label Licensing</h3>
              <p><strong>Pricing:</strong> From $3,000 USD/year (brand customization, joint development)</p>
              <p><strong>Refund Condition:</strong> Refund if 1000 hours of analyzable content is reached (condition: average 80+ score sentences, only occasional incorrect pronunciation words).</p>
            </div>

            <div className="business-model">
              <h3>6. B2B2C Strategic Partner Ecosystem</h3>
              <p><strong>Commission Sharing:</strong> 15-30% (schools, study abroad agencies, immigration consultants recommendations)</p>
              <p><strong>Learning Progress Plan:</strong> $3-4 USD/month/person + certification fees</p>
            </div>

          </section>

          <section className="pitch-section">
            <h2>Competitive Advantages</h2>
            
            <div className="advantage">
              <h3>1. Technical Barriers</h3>
              <p>Azure deep integration, proprietary AI algorithms, multi-modal processing. We provide 34 languages and data monetization capabilities.</p>
            </div>

            <div className="advantage">
              <h3>2. User Experience</h3>
              <p>Intuitive interface, personalized paths, cross-platform sync with community features and refund incentives.</p>
            </div>

            <div className="advantage">
              <h3>3. Ecosystem</h3>
              <p>Partnerships with educational institutions and study abroad agencies; data sales create unique moat for sustainable competitive advantage.</p>
            </div>
          </section>

          <section className="pitch-section">
            <h2>Partner Ecosystem</h2>
            <ul>
              <li><strong>Educational Institutions:</strong> Learning progress assessment, $3-4 USD/month/person</li>
              <li><strong>API Partnerships:</strong> Teacher embedding tools, including teacher points mall</li>
              <li><strong>Study Abroad/Immigration Alliance:</strong> 15-30% commission + smart recommendations</li>
              <li><strong>AI Company Partners:</strong> Data sales cooperation (such as speechsuper.com)</li>
            </ul>
          </section>

          <section className="pitch-section">
            <h2>Financial Projections</h2>
            <p>Based on conservative estimates (20% user growth rate, 30% data consent rate, 20% market penetration), using unified USD pricing. Assuming initial 10,000 users, growing to 5 million; Azure costs $5,000 USD monthly (increases with usage).</p>

            <div className="financial-table">
              <h3>3-Year Financial Blueprint (USD Millions)</h3>
              
              <table className="financial-breakdown">
                <thead>
                  <tr>
                    <th>Item</th>
                    <th>Year 1 (Launch)</th>
                    <th>Year 2 (Growth)</th>
                    <th>Year 3 (Expansion)</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td><strong>Total Revenue</strong></td>
                    <td>$12M</td>
                    <td>$44M</td>
                    <td>$125M</td>
                  </tr>
                  <tr>
                    <td>B2C Subscriptions ($10/month, free clause)</td>
                    <td>$6M (100K users, 50% paid)</td>
                    <td>$15M (200K users, 40% paid)</td>
                    <td>$31M (500K users, 30% paid)</td>
                  </tr>
                  <tr>
                    <td>B2B/API/Licensing (with refunds)</td>
                    <td>$3M (adjusted revenue, refund deduction $0.6M)</td>
                    <td>$12M (growth, refund deduction $1.5M)</td>
                    <td>$37M (scale, refund deduction $3M)</td>
                  </tr>
                  <tr>
                    <td>Partner Revenue Sharing</td>
                    <td>$1.5M</td>
                    <td>$6M</td>
                    <td>$15M</td>
                  </tr>
                  <tr>
                    <td>Data Sales</td>
                    <td>$1.5M (50 hours/month @$200/hour, high quality boost value)</td>
                    <td>$9M (200 hours/month, refund contributed data)</td>
                    <td>$41M (500 hours/month, royalty contribution)</td>
                  </tr>
                  <tr>
                    <td><strong>Total Costs</strong></td>
                    <td>$9M (marketing $3M, development $3M, Azure $3M)</td>
                    <td>$25M (including data processing $6M)</td>
                    <td>$62M (global expansion $15M)</td>
                  </tr>
                  <tr>
                    <td><strong>Net Profit</strong></td>
                    <td>$3M</td>
                    <td>$19M</td>
                    <td>$63M</td>
                  </tr>
                  <tr>
                    <td><strong>Profit Margin</strong></td>
                    <td>25%</td>
                    <td>43%</td>
                    <td>50%</td>
                  </tr>
                  <tr>
                    <td><strong>User Count</strong></td>
                    <td>100K</td>
                    <td>300K</td>
                    <td>1M</td>
                  </tr>
                </tbody>
              </table>

              <div className="key-assumptions">
                <h4>Key Assumptions:</h4>
                <ul>
                  <li><strong>Year 1:</strong> Unified USD pricing but data sales compensation (contributing 20%); refund conditions improve data quality, sales revenue increase 15%</li>
                  <li><strong>Year 2:</strong> Global expansion contributes 30% revenue</li>
                  <li><strong>Year 3:</strong> Achieve 20% market share</li>
                </ul>
              </div>

              <p><strong>Summary:</strong> 3-year cumulative revenue $181 million USD, net profit $85 million USD. Data sales contribute 18% revenue, with higher potential if partnering with speechsuper.com and others.</p>
            </div>
          </section>

          <section className="pitch-section">
            <h2>Team Introduction</h2>
            <p><strong>Founder/CEO:</strong> Yichi Wang</p>
            <p>Team inspiration comes from notegpt.io's AI product innovation model, focusing on efficient development and user-oriented approach.</p>
          </section>

          <section className="pitch-section">
            <h2>Conclusion & Call to Action</h2>
            <p>nicetone.ai is not just a learning platform, but a data-driven educational ecosystem. Our pricing, refund, and data sales model enables sustainable growth, capturing the trillion-dollar opportunity in the AI voice market. Invest in us, invest in the future of education! Contact us to discuss partnerships or experience the product: nicetone.ai.</p>
          </section>

          <div className="pitch-footer">
            <p><strong>Investment Opportunity:</strong> Join the AI Education Revolution!</p>
            <p>Contact: <a href="mailto:contact@nicetone.ai">contact@nicetone.ai</a> | Website: <a href="https://nicetone.ai">nicetone.ai</a></p>
          </div>
        </div>
      </div>
    );
  }

  // Chinese Version
  return (
    <div className="pitch-details">
      <div className="container">
        <header className="pitch-header">
          <h1>nicetone.ai 商業提案</h1>
          <p className="pitch-tagline">靠著聲音數據銷售賺錢的 AI 英文訓練平台</p>
        </header>

        <section className="pitch-section">
          <h2>執行摘要</h2>
          <p>
            nicetone.ai 是一家靠著聲音數據銷售賺錢、接近免費但有飛輪效應的AI英文訓練平台，專注於英語發音學習，
            結合Microsoft Azure語音技術與自主AI分析，為全球語言學習者提供專業級評估、個人化建議和跨裝置學習體驗。
            我們的核心使命是解決傳統英語學習的痛點：缺乏即時回饋、專業資源稀缺和高成本。這一模式透過用戶生成的高品質聲音數據變現，
            形成飛輪效應：更多用戶 → 更多數據 → 更高收入 → 更低成本 → 吸引更多用戶，預計創造可持續成長並吸引投資者。
          </p>
          
          <div className="key-points">
            <h3>核心亮點：</h3>
            <ul>
              <li><strong>市場機會：</strong>全球語言學習市場規模達60億美元，目標服務5,000萬用戶</li>
              <li><strong>市場目標：</strong>佔有20%市場份額，並在10年內擴展至34種語言，達到1,000萬活躍用戶</li>
              <li><strong>革命性數據變現：</strong>聲音數據銷售利潤率比傳統語音識別服務高100倍。處理成本每分鐘$0.01，同樣數據銷售給AI公司每分鐘可獲得$1+，創造前所未有的利潤率</li>
              <li><strong>整合商業模式：</strong>數據優先營收策略，結合聲音數據銷售（主要）、B2C訂閱（10 USD/月含數據換免費）、B2B解決方案、API整合、白標授權和策略夥伴生態</li>
              <li><strong>競爭優勢：</strong>頂尖技術整合（Azure深度合作）、個人化用戶體驗和數據驅動生態系統</li>
              <li><strong>財務預測：</strong>3年內實現年營收1.25億美元，淨利潤率25%，預期ROI高達300%</li>
              <li><strong>融資需求：</strong>尋求500萬美元種子輪，用於產品優化、市場擴張和數據基礎設施</li>
            </ul>
          </div>
        </section>

        <section className="pitch-section">
          <h2>市場痛點</h2>
          <p>當前英語發音學習市場面臨核心挑戰：</p>
          
          <div className="pain-point">
            <h3>1. 傳統學習效率低</h3>
            <p>缺乏個人化回饋和科學評估，學習者難以自我診斷音素錯誤。</p>
            <ul>
              <li>無法即時提供精確評估，無法因材施教</li>
              <li>缺乏音素級別的錯誤分析</li>
              <li>學習者難以自我診斷發音問題</li>
              <li>傳統教學無法因材施教</li>
            </ul>
          </div>

          <div className="pain-point">
            <h3>2. 資源稀缺且成本高</h3>
            <p>專業教師短缺，一對一指導昂貴，地理限制機會。</p>
            <ul>
              <li>專業發音教師資源短缺</li>
              <li>一對一指導成本昂貴</li>
              <li>地理位置限制學習機會</li>
              <li>缺乏標準化評估工具</li>
            </ul>
          </div>

          <div className="pain-point">
            <h3>3. 缺乏標準工具</h3>
            <p>這些痛點導致全球語言學習者流失率高達50%，市場需求未被滿足。相較於 engsight-lab.com（聚焦全球化語言學習），我們更注重AI驅動的即時評估和數據變現。</p>
          </div>
        </section>

        <section className="pitch-section">
          <h2>解決方案</h2>
          <p>nicetone.ai 提供全方位的AI發音學習平台，基於Microsoft Azure語音服務和自主AI算法：</p>

          <div className="solution-feature">
            <h3>1. 智慧發音評估引擎</h3>
            <p>四維度評分（準確度、流暢度、完整度、韻律），音素級分析，即時回饋。</p>
          </div>

          <div className="solution-feature">
            <h3>2. AI個人化學習助理</h3>
            <p>分析學習歷程，提供動態內容推薦、錯誤模式識別和進度追蹤。</p>
          </div>

          <div className="solution-feature">
            <h3>3. 雲端協作生態</h3>
            <p>跨裝置同步、社群分享和企業管理工具。</p>
          </div>

          <div className="solution-feature">
            <h3>4. 創新教育模式</h3>
            <p>以學習歷程取代單次考試，支援API整合至LMS系統（如 teachify.tw 的線上課程平台，可無縫嵌入我們的API）。</p>
          </div>

          <div className="solution-feature">
            <h3>5. 核心功能</h3>
            <p>即時錄音評估、多模態輸入（文字、語音、圖片）、語音合成、收藏系統和AI助理。</p>
          </div>

          <p>平台設計模組化，確保可擴展性和靈活性，為未來擴展做好準備。</p>
        </section>

        <section className="pitch-section">
          <h2>目前產品進度</h2>
          <p>產品開發已幾乎完成，除了多語言支援、學習進度追蹤、Widget和API整合尚未完工以外，大部分功能都已就緒。這包括核心發音評估引擎、AI學習助理、雲端同步和用戶介面，準備好進入市場測試和優化階段。</p>
        </section>

        <section className="pitch-section">
          <h2>市場機會</h2>
          <ul>
            <li><strong>全球市場：</strong>60億美元規模，目標5,000萬用戶、30,000企業客戶、20%佔有率</li>
            <li><strong>全球擴展：</strong>支援34種語言，目標1,000萬活躍用戶，年營收15億美元，10年佈局</li>
            <li><strong>數位學習趨勢：</strong>COVID後成長30%和AI教育需求（預計市場達600億美元）提供龐大機會。借鏡 ycombinator.com（Mathos的AI數學學習工具，強調個人化教育），我們聚焦語音領域的適性學習。</li>
          </ul>
        </section>

        <section className="pitch-section">
          <h2>商業模式</h2>
          <p>我們的革命性商業模式以聲音數據變現為核心，利潤率比傳統語音處理高100倍。Azure語音識別成本每分鐘$0.01，同樣的匿名化錯誤數據銷售給AI公司每分鐘可獲得$1+，創造前所未有的獲利能力。這種數據優先策略讓我們能提供接近免費的服務，同時建立跨B2C、B2B和B2B2C的可持續營收流。</p>

          <div className="business-model">
            <h3>1. 聲音數據銷售（Voice Data Monetization）</h3>
            <p><strong>革命性經濟效益：</strong>100倍利潤率優勢 - Azure處理成本每小時$0.60，同樣音頻內容數據銷售可獲得$60-300/小時。</p>
            <p><strong>頂級數據價值：</strong>錯誤發音片段對訓練語音識別模型的AI公司價值每小時$100-500，因為錯誤發音數據極其稀有且珍貴。</p>
            <p><strong>巨大獲利潛力：</strong>預計每月100小時頂級數據銷售可獲得$10,000-30,000，營運成本低於$300，創造97%+毛利率。</p>
            <p><strong>飛輪效應：</strong>免費用戶產生珍貴數據 → 高利潤銷售收入 → 補貼免費服務 → 吸引更多用戶 → 數據價值指數成長。</p>
          </div>

          <div className="business-model">
            <h3>2. B2C 訂閱服務</h3>
            <p><strong>基本定價：</strong>10 USD/月（含無限評估、AI助理、雲端同步）</p>
            <p><strong>高使用免費條款：</strong>如果用戶每月使用超過5小時（e.g., 練習錄音總時長），即可免費使用該月。但服務合約（Terms of Service）中明確規定：用戶聲音數據將被匿名化用於協助製作語音辨識引擎（e.g., 訓練AI模型），且需符合高品質條件（平均80分以上的句子，只能偶爾穿差幾個發音不好的單字）。這鼓勵高參與度，產生更多niche數據（錯誤發音片段），並符合隱私法規（如GDPR）。</p>
            <p><strong>預期效果：</strong>吸引價格敏感用戶，轉化率提升20%；數據同意率預計30%，產生每月數百小時可銷售語料。</p>
          </div>

          <div className="business-model">
            <h3>3. B2B 企業解決方案</h3>
            <p><strong>定價：</strong>3,000 USD/年起（客製化功能、管理後台、報告）</p>
            <p><strong>退費條件：</strong>只要達到1000小時的可供分析內容就可退費（條件：平均80分以上的句子，只能偶爾穿差幾個發音不好的單字）。這鼓勵企業產生高品質數據，用於我們的數據銷售管道。</p>
            <p><strong>目標：</strong>企業員工培訓和教育機構。</p>
          </div>

          <div className="business-model">
            <h3>4. 教學 API 整合服務</h3>
            <p><strong>定價：</strong>6 USD/月/學生（API調用、成績分析、支援）</p>
            <p><strong>退費條件：</strong>只要達到5小時的可供分析內容就可退費100%（條件：平均80分以上的句子，只能偶爾穿差幾個發音不好的單字）。這部分由學生家長支付購買服務，但老師可以收回扣（有點數在商城換產品，如教育工具或課程資源）。</p>
            <p><strong>功能：</strong>無縫嵌入LMS系統（如 teachify.tw 的整合兼容）。</p>
            <p><strong>預期效果：</strong>老師激勵機制提升採用率20%，同時產生更多高品質數據。</p>
          </div>

          <div className="business-model">
            <h3>5. White Label 授權</h3>
            <p><strong>定價：</strong>3,000 USD/年起（品牌客製、共同開發）</p>
            <p><strong>退費條件：</strong>只要達到1000小時的可供分析內容就可退費（條件：平均80分以上的句子，只能偶爾穿差幾個發音不好的單字）。</p>
          </div>

          <div className="business-model">
            <h3>6. B2B2C 策略夥伴生態</h3>
            <p><strong>佣金分潤：</strong>15-30%（學校、留學代辦、移民顧問推薦）</p>
            <p><strong>學習歷程方案：</strong>3-4 USD/月/人 + 認證費</p>
          </div>

        </section>

        <section className="pitch-section">
          <h2>競爭優勢</h2>
          
          <div className="advantage">
            <h3>1. 技術壁壘</h3>
            <p>Azure深度整合、自主AI算法、多模態處理。我們提供34種語言和數據變現能力。</p>
          </div>

          <div className="advantage">
            <h3>2. 用戶體驗</h3>
            <p>直覺介面、個人化路徑、跨平台同步，包含社群功能和退費激勵機制。</p>
          </div>

          <div className="advantage">
            <h3>3. 生態系統</h3>
            <p>與教育機構、留學代辦合作；數據銷售創造獨特護城河，形成可持續競爭優勢。</p>
          </div>
        </section>

        <section className="pitch-section">
          <h2>夥伴生態</h2>
          <ul>
            <li><strong>教育機構：</strong>學習歷程評估，3-4 USD/月/人</li>
            <li><strong>API合作：</strong>教師嵌入工具，含老師點數商城</li>
            <li><strong>留學/移民聯盟：</strong>15-30%佣金 + 智慧推薦</li>
            <li><strong>AI公司夥伴：</strong>數據銷售合作（如 speechsuper.com）</li>
          </ul>
        </section>

        <section className="pitch-section">
          <h2>財務預測</h2>
          <p>基於保守估計（用戶成長率20%、數據同意率30%、市場滲透20%），並使用統一美元定價。假設初始用戶1萬，成長至500萬；Azure成本每月5,000 USD（隨用量增）。</p>

          <div className="financial-table">
            <h3>3年財務藍圖（單位：百萬美元）</h3>
            
            <table className="financial-breakdown">
              <thead>
                <tr>
                  <th>項目</th>
                  <th>年1 (啟動)</th>
                  <th>年2 (成長)</th>
                  <th>年3 (擴張)</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td><strong>總營收</strong></td>
                  <td>12</td>
                  <td>44</td>
                  <td>125</td>
                </tr>
                <tr>
                  <td>B2C訂閱（10 USD/月，含免費條款）</td>
                  <td>6 (10萬用戶，50%付費)</td>
                  <td>15 (20萬用戶，40%付費)</td>
                  <td>31 (50萬用戶，30%付費)</td>
                </tr>
                <tr>
                  <td>B2B/API/授權（含退費）</td>
                  <td>3 (調整後收入，退費扣減0.6）</td>
                  <td>12 (成長，退費扣減1.5）</td>
                  <td>37 (規模化，退費扣減3）</td>
                </tr>
                <tr>
                  <td>夥伴分潤</td>
                  <td>1.5</td>
                  <td>6</td>
                  <td>15</td>
                </tr>
                <tr>
                  <td>數據銷售</td>
                  <td>1.5 (50小時/月@200 USD/小時，高品質提升價值)</td>
                  <td>9 (200小時/月，退費貢獻數據)</td>
                  <td>41 (500小時/月，版稅貢獻)</td>
                </tr>
                <tr>
                  <td><strong>總成本</strong></td>
                  <td>9 (行銷3、開發3、Azure3)</td>
                  <td>25 (含數據處理6)</td>
                  <td>62 (全球擴張15)</td>
                </tr>
                <tr>
                  <td><strong>淨利潤</strong></td>
                  <td>3</td>
                  <td>19</td>
                  <td>63</td>
                </tr>
                <tr>
                  <td><strong>利潤率</strong></td>
                  <td>25%</td>
                  <td>43%</td>
                  <td>50%</td>
                </tr>
                <tr>
                  <td><strong>用戶數</strong></td>
                  <td>10萬</td>
                  <td>30萬</td>
                  <td>100萬</td>
                </tr>
              </tbody>
            </table>

            <div className="key-assumptions">
              <h4>關鍵假設：</h4>
              <ul>
                <li><strong>年1：</strong>定價統一美元但數據銷售彌補（貢獻20%）；退費條件提升數據品質，銷售收入增15%</li>
                <li><strong>年2：</strong>全球擴張貢獻30%營收</li>
                <li><strong>年3：</strong>達到20%市場佔有率</li>
              </ul>
            </div>

            <p><strong>總結：</strong>3年累計營收181百萬美元，淨利85百萬美元。數據銷售貢獻18%營收，潛力更高若與 speechsuper.com 等合作。</p>
          </div>
        </section>

        <section className="pitch-section">
          <h2>團隊介紹</h2>
          <p><strong>創辦人/CEO：</strong>王意騏 Yichi Wang</p>
          <p>團隊靈感來自 notegpt.io 的AI產品創新模式，聚焦高效開發和用戶導向。</p>
        </section>

        <section className="pitch-section">
          <h2>結論與行動呼籲</h2>
          <p>nicetone.ai 不僅是學習平台，更是數據驅動的教育生態系統。定價、退費和數據銷售模式讓我們實現可持續成長，抓住AI語音市場的千億機會。投資我們，即投資未來教育！聯繫我們討論合作或體驗產品：nicetone.ai。</p>
        </section>

        <div className="pitch-footer">
          <p><strong>投資機會：</strong>加入 AI 教育革命！</p>
          <p>聯繫方式：<a href="mailto:contact@nicetone.ai">contact@nicetone.ai</a> | 網站：<a href="https://nicetone.ai">nicetone.ai</a></p>
        </div>
      </div>
    </div>
  );
}