name: CI Tests

on:
  pull_request:
    branches: [ main, master, develop ]
  push:
    branches: [ main, master, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run Jest unit tests
      run: npm run test:ci
      timeout-minutes: 5
      
    - name: Cache Playwright browsers
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/ms-playwright
        key: playwright-chrome-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          playwright-chrome-${{ runner.os }}-
      
    - name: Install Playwright Chrome only
      run: npx playwright install chromium
      timeout-minutes: 10
      
    - name: Run Playwright E2E tests (Chrome only)
      run: npm run test:e2e:ci -- --update-snapshots
      timeout-minutes: 8
      env:
        CI: true
        HEADLESS: true
        
    - name: Upload Playwright Report
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report-${{ matrix.node-version }}
        path: playwright-report/
        retention-days: 30
        if-no-files-found: error
        
    - name: Upload Jest Coverage
      uses: actions/upload-artifact@v4
      with:
        name: jest-coverage-${{ matrix.node-version }}
        path: coverage/
        retention-days: 30
        if-no-files-found: error

  visual-regression:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'pull_request'
    timeout-minutes: 15
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Cache Playwright browsers
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/ms-playwright
        key: playwright-chrome-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          playwright-chrome-${{ runner.os }}-
      
    - name: Install Playwright Chrome only
      run: npx playwright install chromium
      timeout-minutes: 10
      
    - name: Run Visual Regression Tests (Chrome only)
      run: npm run test:e2e:ci -- --update-snapshots
      timeout-minutes: 8
      env:
        CI: true
        HEADLESS: true
        
    - name: Upload Visual Regression Report
      uses: actions/upload-artifact@v4
      with:
        name: visual-regression-report
        path: test-results/
        retention-days: 30
        if-no-files-found: error 